# -*- coding: utf-8 -*-
"""Design of a Dynamic Ticketing System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-YDoY2wJD8YnIvXhMv0CnAFPCSMwQCU4

PART A: Ticket Booking
"""

#define the Ticketingsystem class
class TicketingSystem:
    def __init__(self):
      # create 2D list 20 rows with 25 seats (total 500 seats)
        # Each seat initialized as "Available"
        self.seats = [["Available"] * 25 for i in range(20)]  # 500 seats
        #dictionary to store booking information, ticket ID as the key
        self.bookings = {}  # stores ticket details
        # waitlist to hold customers if requested seat is taken
        # each item in the list is a tuple
        self.waitlist = []  # simple priority-based waitlist

    def book_ticket(self, name, seat_row, seat_col, priority):
      # Checks if the requested seat is available
        if self.seats[seat_row][seat_col] == "Available":
          # create a unique ticket ID using row, column, and priority
            ticket_id = f"{seat_row}{seat_col}P{priority}"  # Unique Ticket ID
            # marks seat booked with ticket ID
            self.seats[seat_row][seat_col] = ticket_id
            # Store booking info in the dictionary
            self.bookings[ticket_id] = {"Name": name, "Seat": (seat_row, seat_col), "Priority": priority}
            # confirmation message
            print(f"Booked! Your ticket ID: {ticket_id}")
        else:
          # if seat taken, adds user to waitlist
            print("Seat taken! Adding to waitlist.")
            self.waitlist.append((priority, name, seat_row, seat_col))
            self.waitlist.sort()  # Sorting by priority

"""PART B: Ticket Cancellation"""

def cancel_ticket(self, ticket_id):
    #check if ticket ID exists in bookings
        if ticket_id in self.bookings:
          #getting seat info from the booking
            seat_row, seat_col = self.bookings[ticket_id]["Seat"]
          #mark seat as available
            self.seats[seat_row][seat_col] = "Available"
        #remove booking from the dictionary
            self.bookings.pop(ticket_id)
            print("Ticket canceled.")


          #If people in the waitlist assign the now-free seat based on priority
            if self.waitlist:
          #get the highest priority person (first item after sorting)
                next_customer = self.waitlist.pop(0)
         #book next seat for this next customer
                self.book_ticket(next_customer[1], seat_row, seat_col, next_customer[0])
        else:
          # message if the ticket ID is not valid
            print("Invalid ticket ID.")

"""PART C: Modify Ticket"""

def modify_ticket(self, ticket_id, new_seat_row, new_seat_col):
      # first check if the ticket exists
        if ticket_id in self.bookings:
        #get current booking details
            name = self.bookings[ticket_id]["Name"]
            priority = self.bookings[ticket_id]["Priority"]
            seat_row, seat_col = self.bookings[ticket_id]["Seat"]
           #free up old seat
            self.seats[seat_row][seat_col] = "Available"
          #remove old booking
            self.bookings.pop(ticket_id)
          #booking new seat
            self.book_ticket(name, new_seat_row, new_seat_col, priority)
            print("Ticket modified.")
          #if ticket ID invalid
        else:
            print("Invalid ticket ID.")

"""PART D: Priority Handling and Dynamic Array Expansion:"""

def expand_seating(self):
      # Create 4 new rows of 25 seats, initialized as "Available"
        new_seats = [["Available"] * 25 for i in range(4)]  # Adding 100 more seats
        # Add new rows to current seating
        self.seats.extend(new_seats)
        print("Seating capacity expanded to 600!")

"""PART E: Hash Table for Fast Lookups"""

def lookup_ticket(self, ticket_id):
      # check if ticket id exists in bookings
        if ticket_id in self.bookings:
          # getting ticket details
            details = self.bookings[ticket_id]
            print(f"Ticket Details for {ticket_id}: Name: {details['Name']}, Seat: {details['Seat']}, Priority: {details['Priority']}")
        else:
          # if ticket not found
            print("Ticket ID not found.")

"""FULL CODE"""

class TicketingSystem:
    def __init__(self):
        self.seats = [["Available"] * 25 for i in range(20)]
        self.bookings = {}
        self.waitlist = []

    # A. Ticket Booking
    def book_ticket(self, name, seat_row, seat_col, priority):
        if self.seats[seat_row][seat_col] == "Available":
            ticket_id = f"{seat_row}{seat_col}P{priority}"
            self.seats[seat_row][seat_col] = ticket_id
            self.bookings[ticket_id] = {"Name": name, "Seat": (seat_row, seat_col), "Priority": priority}
            print(f"Booked! Your ticket ID: {ticket_id}")
        else:
            print("Seat taken! Adding to waitlist.")
            self.waitlist.append((priority, name, seat_row, seat_col))
            self.waitlist.sort()

    # B. Ticket Cancellation
    def cancel_ticket(self, ticket_id):
        if ticket_id in self.bookings:
            seat_row, seat_col = self.bookings[ticket_id]["Seat"]
            self.seats[seat_row][seat_col] = "Available"
            self.bookings.pop(ticket_id)
            print("Ticket canceled.")

            if self.waitlist:
                next_customer = self.waitlist.pop(0)
                self.book_ticket(next_customer[1], seat_row, seat_col, next_customer[0])
        else:
            print("Invalid ticket ID.")

    # C. Modify Ticket
    def modify_ticket(self, ticket_id, new_seat_row, new_seat_col):
        if ticket_id in self.bookings:
            name = self.bookings[ticket_id]["Name"]
            priority = self.bookings[ticket_id]["Priority"]
            seat_row, seat_col = self.bookings[ticket_id]["Seat"]
            self.seats[seat_row][seat_col] = "Available"
            self.bookings.pop(ticket_id)
            self.book_ticket(name, new_seat_row, new_seat_col, priority)
            print("Ticket modified.")
        else:
            print("Invalid ticket ID.")

    # D. Priority Handling and Dynamic Array Expansion
    def expand_seating(self):
        new_seats = [["Available"] * 25 for i in range(4)]
        self.seats.extend(new_seats)
        print("Seating capacity expanded to 600!")

    # E. Hash Table for Fast Lookups
    def lookup_ticket(self, ticket_id):
        if ticket_id in self.bookings:
            details = self.bookings[ticket_id]
            print(f"Ticket Details for {ticket_id}: Name: {details['Name']}, Seat: {details['Seat']}, Priority: {details['Priority']}")
        else:
            print("Ticket ID not found.")